// <auto-generated />
using System;
using HRM.A;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRM.A.Migrations
{
    [DbContext(typeof(HRMContext))]
    partial class HRMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRM.A.Models.HRM_ACTIVITY_STAT", b =>
                {
                    b.Property<string>("ActivityCd")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivityNm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IUsr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UUsr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityCd");

                    b.ToTable("HRM_ACTIVITY_STATs");
                });
#pragma warning restore 612, 618
        }
    }
}
